erDiagram
    USERS{
        int id PK
        string username
        string password
        string email
        variable __
        int group_id FK
        timestamp created_at
        timestamp updated_at
    }
    PRIVILEGES {
        string id PK
        string name
        string description
    }
    PRIVILEGES_GROUPS {
        int group_id FK
        int privilege_id FK
    }
    GROUPS {
        int id PK
        string name
        string description
    }
    USER_GROUP {
        int group_id FK
        int user_id FK
    }
    AUDIT_TRAIL {
        int id PK
        int user_id FK
        string activity_name
        string status
        string description
    }
    SPRINT {
        int id PK
        string name
        string description
    }

    ACTIVITY {
        int id PK
        int sprint_id FK
        string name
        string description
    }

    TASK {
        int id PK
        int activity_id FK
        string name
        string description
    }

    MILESTONE {
        int id PK
        int task_id FK
        string name
        string description
    }

    RESOURCE {
        int id PK
        int user_id FK
        int parameter_id FK
    }

    RESOURCE_PRIVILEGE {
        int resource_id FK
        int privilege_id FK
    }

    USER_SUBGROUP {
        int subgroup_id FK
        int user_id FK
    }

    SUBGROUP {
        int id PK
        int group_id FK
        int parameter_id FK
    }
    SUBGROUP_PRIVILEGES {
        int subgroup_id FK
        int privilege_id FK
    }

    PARAMETER {
        int id PK
        int key "dbName.tableName.id"
        int value "id number"
    }

    USERS ||--|{ USER_GROUP : "users have many group"
    GROUPS ||--|{ USER_GROUP : "1 or more groups can be acquired by user"
    GROUPS ||--|{ PRIVILEGES_GROUPS : "groups may have many"
    PRIVILEGES ||--|{ PRIVILEGES_GROUPS : "to many privileges"
    USERS }|--o| AUDIT_TRAIL : "all user may has an audit trail"
    SPRINT ||--|{ ACTIVITY : "sprint have many activity"
    TASK }|--|| ACTIVITY : "activity have many tasks"
    TASK ||--|{ MILESTONE : "have many milestone"
    USERS ||--|{ USER_SUBGROUP : "have many"
    SUBGROUP ||--|{ USER_SUBGROUP : "have many"
    PRIVILEGES ||--|{ SUBGROUP_PRIVILEGES : "many"
    SUBGROUP ||--|{ SUBGROUP_PRIVILEGES : "many"
    SUBGROUP ||--|| PARAMETER : "many"
    USERS ||--|{ RESOURCE : "many"
    RESOURCE ||--|{ RESOURCE_PRIVILEGE : "many"
    PRIVILEGES ||--|{ RESOURCE_PRIVILEGE : "many"
    RESOURCE ||--|| PARAMETER : "one"




